### ISSUE TITLE
We need main to generate a graphic of the end-state to provide documentation for the paper

### ISSUE THREAD

**Issue by MikeWorden** [tartona/cs540teamk#10]
Implied requirement

**Comment by icziemba** [comment]
We can use drone_world_figure.py for this. It uses matplot to generate a 3D snapshot of a drone world.

**Comment by MikeWorden** [comment]
Looks good.    We'll have to programmatically adjust the max-dimensions to provide a useable picture based on the dimensions of the start and goal state.
