### ISSUE TITLE
We need the Low Level Planner to  move the block to a target location, given a drone location, a block location and a block target location.

### ISSUE THREAD

**Issue by MikeWorden** [tartona/cs540teamk#15]

**Comment by icziemba** [comment]
The current implementation uses a local greedy search with a Tabu structure to navigate around obstacles. With this implementation should be fast, it will have issues with complex obstacles. For example, thin columns should not be an issue, but long walls would be.

**Comment by MikeWorden** [comment]
Will consider it closed.  Actually thin columns and low walls should be fine.   Just obstacles that are wide in more than 1 dimension are difficult.
