### ISSUE TITLE
We need a main subroutine that reads the start state and end state

### ISSUE THREAD

**Issue by MikeWorden** [tartona/cs540teamk#2]
We need a main subroutine that reads in the start state & end state

**Comment by icziemba** [comment]
The drone_world.py reads in the start state with initialize(). It uses the CSV package with the deliminator set to space which seems to conform to the expected input file. From there, it will generate all the objects (blocks and drones) in the drone world.

The end state should be read in by the high level planner. In csa_planner.py, I put a initialize() function there which reads in the end state. But, I have not tried it to verify it works.

**Comment by MikeWorden** [comment]
I'm closing this.   Nice visualization, although we'll likely have to adjust the visualization parameters based on our problem (the GUI is not helpful here).
Noted that the  **10 10 0 blue** line resulted in a blue block at 10, 0, 0.
