### ISSUE TITLE
We need the High Level Planner to return a count of moves and a summary of processing time

### ISSUE THREAD

**Issue by MikeWorden** [tartona/cs540teamk#9]
From the assumptions, the HL Planner is responsible for:
•	Accounting for all moves
•	Accounting for all compute time

**Comment by icziemba** [comment]
I changed drone_world_object.py around to include a move counter for all objects (blocks and drone). I added get_drone_move_counter() to drone_world.py so that we can get this information. So, the high level planner does not need to worry about recording moves.

**Comment by MikeWorden** [comment]
Agreed.  Closed as invalid
